### ISSUE TITLE
Spelling Correction on index.html

### ISSUE THREAD

**Issue by k4tt4b3** [Benja-media/Ulink#28]
Current spelling on line 39 for attribution:

`<p id="Atrubution" class="atr"></p>`

Correct one:
`<p id="Attribution" class="atr"></p>`

Ps. Loving the project, setting this on Instagram 😄

**Comment by Benjamin-del** [comment]
Thanks for pointing out! I will fix this soon!

**Comment by Benjamin-del** [comment]
If you don't mind me asking, Where did you find out about Ulink?

**Comment by k4tt4b3** [comment]
Browsing through here and realised the usefulness of this 🙌
